### PR TITLE
Converted to .NET Standard

### PR DESCRIPTION
**Pull request by RedZone908**

### CODE REVIEW

**Review by bgrainger — CHANGES_REQUESTED** [review]
* The existing directory structure was good; please don't change it.
* The `.vs/` folder should be gitignore'd, not added to the repo.
* Don't change whitespace.
* The `[ExpectedException]` change is good, but should be done as a separate PR.
* Overall, it seems like multiple changes (csproj format, test library, build script) are being conflated into one PR, and could be committed separately.

**Comment by RedZone908** [comment]
Hey, thanks for your honest feedback! This is my first time committing to a public Github, so I have a lot to learn!

I tried to keep the existing directory structure where I could. I think the only thing I left out was some of the directories for "tools" and some of the PS scripts, things that I wasn't sure how to test out. Before the next time I do a pull request I can put those back in but, I can't guarantee right away that those tools and scripts and such will work with .NET Core/Standard, it might have to be a separate PR where I get those figured out. 

Oh, yeah, the lib directory is missing. I can put that back.

In the future I can make sure that I separate these things out into multiple pull requests, but I don't know how easy it will be to retroactively do that now. I apologize for all the mistakes! Like I said, I am very new at maintaining any code besides my own company's.

**Comment by RedZone908** [comment]
Blink oh. and I totally nested the entire directory structure. Did not mean to do that at all. That can be fixed.

**Comment by bgrainger** [comment]
BTW, this code will be archived soon (#22) so we won't be accepting any contributions. Our latest utility library is at https://github.com/Faithlife/FaithlifeUtility (and is already netstandard).

**Pull request closed without merging**
